version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: helio@123
      POSTGRES_DB: products_db
    ports:
      - 5432:5432
    hostname: localhost
    